#!/bin/bash
# Runs inside the freshly pacstrapped rootfs, under arch-chroot.
#
# Everything here is the part of "an installed system" that pacstrap does not
# do: identity, fstab, initramfs, the user, and what starts the session.
#
# Environment in: GUEST_USER GUEST_HOST ROOT_UUID ESP_UUID VERSION COMMIT
#                 OMARCHY_VERSION OMARCHY_REF
#                 SSH_PUBKEY (optional)
set -euo pipefail

say() { printf '    \033[1m%s\033[0m\n' "$*"; }

# ---------------------------------------------------------------------------
say "identity"
echo "$GUEST_HOST" >/etc/hostname
ln -sf /usr/share/zoneinfo/UTC /etc/localtime
# The guest's clock comes from the host through KVM/HVF, and tzupdate (which
# upstream uses to set this from geolocation) has no aarch64 package.
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen >/dev/null
echo 'LANG=en_US.UTF-8' >/etc/locale.conf
echo 'KEYMAP=us' >/etc/vconsole.conf

cat >/etc/hosts <<EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   $GUEST_HOST.localdomain $GUEST_HOST
EOF

# ---------------------------------------------------------------------------
say "fstab"
# By PARTUUID, which build-disk.sh pins to a fixed value rather than letting
# sgdisk generate one -- so this file is the same in every build and an image
# rebuilt tomorrow boots the same way.
#
# The ESP is mounted at /boot, not /efi. That is what makes an in-guest
# `pacman -Syu` that bumps linux-aarch64 write the new kernel somewhere the
# firmware can read: pacman puts it in /boot/Image, mkinitcpio writes
# /boot/initramfs-linux.img beside it, and systemd-boot's entry names both.
# With /boot inside the ext4 root instead, a kernel upgrade would silently
# leave the ESP holding the old one.
cat >/etc/fstab <<EOF
# <file system>                              <dir>  <type>  <options>                        <dump> <pass>
PARTUUID=$ROOT_UUID  /      ext4    rw,relatime                      0      1
PARTUUID=$ESP_UUID  /boot  vfat    rw,noatime,fmask=0137,dmask=0027  0      2
EOF

# ---------------------------------------------------------------------------
say "initramfs"
# `autodetect` is removed on purpose. It builds an initramfs containing only
# the modules loaded on the machine doing the building -- which here is a
# Docker container on a Mac, whose loaded modules have nothing to do with a
# QEMU virt guest. The result boots to "device did not show up" every time.
# Naming the virtio drivers explicitly costs a few MB and removes the whole
# class of failure.
cat >/etc/mkinitcpio.conf.d/omarchy-mobile.conf <<'EOF'
MODULES=(virtio virtio_pci virtio_blk virtio_scsi virtio_net virtio_gpu virtio_input virtio_console)
HOOKS=(base udev modconf kms block filesystems fsck)
COMPRESSION="zstd"
EOF
mkinitcpio -P

# ---------------------------------------------------------------------------
say "shipped configs -> /etc/skel"
# Omarchy 4.x seeds a new user's ~/.config from /etc/skel; its own package
# builds that from config/. We vendor the source tarball rather than that
# package, so the same seeding happens here.
#
# omarchy-provision-user's help text is the authority: "For shipped configs see
# /etc/skel (new users) and omarchy-reinstall-configs (existing users)".
install -d /etc/skel/.config
cp -a /usr/share/omarchy/config/. /etc/skel/.config/
install -d /etc/skel/.local/state /etc/skel/.local/share

# The panel, from manifest.toml. Upstream ships scale = "auto", which on a
# 720x1440 virtual panel resolves to 1 -- so the bar is 26 physical pixels tall
# and the whole UI is desktop-sized on a screen the shape of a phone. moarchy
# measured the original PinePhone at 720x1440 with `scale 2` -> 360x720
# logical, and that is the geometry this file reproduces.
#
# It is written to ~/.config/hypr/monitors.lua, which is a file UPSTREAM SHIPS
# as a user override and loads after its own defaults:
#
#   require("hypr.monitors")   -- config/hypr/hyprland.lua
#
# so nothing upstream is patched to change it. That is the same move moarchy
# makes with its Sway theme template -- add a file to a directory the upstream
# template engine already reads -- and it is the mechanism the whole mobile
# overlay should be built on.
cat >/etc/skel/.config/hypr/monitors.lua <<EOF
-- Generated by omarchy-mobile from [vm] in manifest.toml. Edit it there.
--
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

hl.env("GDK_SCALE", "$VM_SCALE")
hl.monitor({
  output   = "",
  mode     = "${VM_WIDTH}x${VM_HEIGHT}@75",
  position = "0x0",
  scale    = $VM_SCALE,
})
EOF

# ---------------------------------------------------------------------------
say "mobile window rules"
# What a phone needs from the window manager -- one app per workspace, filling
# it (docs/spec/windows.md W1-W5) -- is hypr/mobile.lua, which the overlay
# put in skel. hyprland.lua is the one user file that names what it loads, and
# its own last comment is where it says personal configuration goes, so the
# require is appended there rather than written into anything upstream owns.
HYPR_USER=/etc/skel/.config/hypr/hyprland.lua
[ -f /etc/skel/.config/hypr/mobile.lua ] || { echo "!! no hypr/mobile.lua -- the overlay did not land in skel" >&2; exit 1; }
[ -f "$HYPR_USER" ] || { echo "!! no $HYPR_USER -- upstream config did not land in skel" >&2; exit 1; }
grep -qF 'require("hypr.mobile")' "$HYPR_USER" \
  || printf '\n-- omarchy-mobile: one app per workspace, filling it.\nrequire("hypr.mobile")\n' >>"$HYPR_USER"

# ---------------------------------------------------------------------------
say "mobile shell plugins"
# This project's own quickshell plugins ship into the directory upstream
# already scans -- ~/.config/omarchy/plugins, seeded from /etc/skel -- rather
# than into a system path. moarchy needed a system path and had to patch
# PluginRegistry to add one; here the user directory costs nothing and buys
# on-device iteration, because the shell reloads a plugin whose files change.
#
# The overlay put the directories there before this script ran. What is left is
# the enabled bit: a third-party plugin is on exactly when its id appears in
# shell.json, so add each one that is not already listed.
#
# The list is DERIVED from what shipped rather than written out here. A second
# plugin is then a directory, not a directory and an edit to this file that
# someone has to remember.
SHELL_JSON=/etc/skel/.config/omarchy/shell.json
PLUGIN_DIR=/etc/skel/.config/omarchy/plugins
if [ -d "$PLUGIN_DIR" ]; then
  [ -f "$SHELL_JSON" ] || { echo "!! no $SHELL_JSON -- upstream config did not land in skel" >&2; exit 1; }
  for manifest in "$PLUGIN_DIR"/*/manifest.json; do
    [ -f "$manifest" ] || continue
    id=$(jq -re '.id' "$manifest") || { echo "!! no id in $manifest" >&2; exit 1; }
    # A plugin that declares kind "bar" is enabled by BEING the bar: the host's
    # PluginRegistry.isEnabled answers for it from `bar.id` alone and ignores
    # the plugins list. mobile.shell is one -- the phone's status bar and the
    # rest of its UI are one switch (Bar.qml).
    is_bar=$(jq '.kinds | index("bar") != null' "$manifest")
    tmp=$(mktemp)
    jq --arg id "$id" --argjson bar "$is_bar" '
      if $bar then .bar.id = $id | .plugins = ((.plugins // []) | map(select(.id != $id)))
      else .plugins = ((.plugins // []) | if any(.id == $id) then . else . + [{id: $id}] end)
      end' "$SHELL_JSON" >"$tmp"
    mv "$tmp" "$SHELL_JSON"
    if [ "$is_bar" = true ]; then say "  enabled $id, as the bar"; else say "  enabled $id"; fi
  done
fi

# ---------------------------------------------------------------------------
say "system users and groups"
# Arch's `filesystem` package no longer ships a populated /etc/group -- it
# ships /usr/lib/sysusers.d/basic.conf and lets systemd-sysusers create the
# groups. Under pacstrap in a container that never runs, so the rootfs arrives
# here with exactly one line in /etc/group:
#
#   root:x:0:root
#
# and the useradd below fails five times over with "group 'wheel' does not
# exist". Running it explicitly is the fix; --root rather than relying on the
# chroot's own systemd, which is not running.
systemd-sysusers >/dev/null 2>&1 || true
systemd-tmpfiles --create >/dev/null 2>&1 || true
for g in wheel video input audio storage users; do
  getent group "$g" >/dev/null || { echo "!! group $g still missing after systemd-sysusers" >&2; exit 1; }
done

# ---------------------------------------------------------------------------
say "user $GUEST_USER"
useradd -m -G wheel,video,input,audio,storage -s /bin/bash "$GUEST_USER"
# No password, and the account is locked rather than blank: the VM's sshd is on
# a port forwarded from the host, and a known password on it would be worse
# than it looks. tty1 autologin is how you get in without one; --ssh-key on the
# build is how you get in over the network.
passwd -l "$GUEST_USER" >/dev/null
passwd -l root >/dev/null
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >/etc/sudoers.d/wheel-nopasswd
chmod 440 /etc/sudoers.d/wheel-nopasswd

if [ -n "${SSH_PUBKEY:-}" ]; then
  say "authorising ssh key"
  install -d -m700 -o "$GUEST_USER" -g "$GUEST_USER" "/home/$GUEST_USER/.ssh"
  printf '%s\n' "$SSH_PUBKEY" >"/home/$GUEST_USER/.ssh/authorized_keys"
  chmod 600 "/home/$GUEST_USER/.ssh/authorized_keys"
  chown "$GUEST_USER:$GUEST_USER" "/home/$GUEST_USER/.ssh/authorized_keys"
fi

# ---------------------------------------------------------------------------
say "services"
systemctl enable systemd-timesyncd.service >/dev/null 2>&1 || true
systemctl enable NetworkManager.service    >/dev/null 2>&1 || true
# Nothing in the session needs to block on DHCP, and letting it hold up
# graphical.target is upstream's own note in install/config/enable-services.sh.
systemctl mask NetworkManager-wait-online.service >/dev/null 2>&1 || true
systemctl enable sshd.service              >/dev/null 2>&1 || true
systemctl enable systemd-oomd.service      >/dev/null 2>&1 || true
systemctl enable power-profiles-daemon.service >/dev/null 2>&1 || true
systemctl enable avahi-daemon.service      >/dev/null 2>&1 || true
systemctl enable seatd.service             >/dev/null 2>&1 || true
# --global, so the unit is wanted by every user's graphical-session.target
# without having to reach into a $HOME that does not exist yet. The unit itself
# comes from this project's default/ overlay, not from upstream.
systemctl --global enable wayvnc.service   >/dev/null 2>&1 || true

# sshd on a locked, passwordless account: keys only, and say so rather than
# relying on the default.
cat >/etc/ssh/sshd_config.d/10-omarchy-mobile.conf <<'EOF'
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
EOF

# ---------------------------------------------------------------------------
say "autologin -> hyprland"
# No display manager. Upstream enables sddm; a phone does not show a login
# screen, and on a software-rendered VM sddm is one more graphical thing that
# can fail before Hyprland gets a chance to. vm/packages/omitted says so too.
install -d /etc/systemd/system/getty@tty1.service.d
cat >/etc/systemd/system/getty@tty1.service.d/autologin.conf <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $GUEST_USER --noclear %I \$TERM
EOF

# uwsm is how Omarchy expects the session to be managed -- its autostart.lua
# imports the environment into the user manager and every app launch goes
# through uwsm-app. Starting bare Hyprland instead leaves those app scopes
# unparented.
#
# `uwsm check may-start` is the guard that keeps this from firing on tty2 or
# over ssh; without it every new login tries to start a second compositor.
cat >"/home/$GUEST_USER/.bash_profile" <<'EOF'
[[ -f ~/.bashrc ]] && . ~/.bashrc

# Start the Hyprland session on tty1 only, and only if one is not running.
if uwsm check may-start >/dev/null 2>&1; then
  exec uwsm start -- hyprland-uwsm.desktop
fi
EOF
chown "$GUEST_USER:$GUEST_USER" "/home/$GUEST_USER/.bash_profile"

# ---------------------------------------------------------------------------
say "icons QtSvg cannot clip"
# QtSvg ignores clip-path, and paints a <clipPath> that is not inside <defs> --
# which is why Web, Geary, Fractal and Dino drew their artwork on a black
# square (docs/build-log.md). omarchy-mobile-icon-repair says every clip path
# as the mask QtSvg does honour, and writes the result into
# /usr/local/share/icons, where every icon lookup in the session -- the shell's
# index, Quickshell.iconPath, GTK -- reaches it before /usr/share.
#
# Here as well as in the pacman hook the overlay just installed: the hook is
# for the transactions to come, and every icon in this image was laid down by
# pacstrap, before there was a hook to fire.
/usr/local/bin/omarchy-mobile-icon-repair

# ---------------------------------------------------------------------------
say "settings the phone overrides"
# The overlay drops .gschema.override files into /usr/share/glib-2.0/schemas
# (today: the mobile user agent Epiphany sends, docs/build-log.md). An override
# is only read out of the compiled gschemas.compiled beside it, and pacstrap
# compiled that before the overlay existed, so it is compiled again here.
#
# pacman's own glib2 hook does this for every transaction that touches a
# schema, which is what keeps the override alive across an upgrade; this is the
# same catch-up the icon repair above needs, for the same reason.
if compgen -G "/usr/share/glib-2.0/schemas/*.gschema.override" >/dev/null; then
  glib-compile-schemas /usr/share/glib-2.0/schemas
  info "$(ls /usr/share/glib-2.0/schemas/*.gschema.override | wc -l) override(s) compiled"
fi

# ---------------------------------------------------------------------------
say "theme bootstrap"
# The whole shell reads its palette from ~/.local/state/omarchy/current/theme.
# Until some theme has been applied that path does not exist, and a shell that
# starts without it comes up unthemed. Upstream's installer applies one; we are
# not running upstream's installer, so a one-shot user unit does it on first
# login and then gets out of the way.
install -d /etc/skel/.config/systemd/user/default.target.wants
cat >/etc/skel/.config/systemd/user/omarchy-mobile-first-run.service <<'EOF'
[Unit]
Description=Apply a default Omarchy theme on first login
ConditionPathExists=!%h/.local/state/omarchy/done/first-run

[Service]
Type=oneshot
# `bash -lc`, not the binary directly. A systemd user service inherits none of
# /etc/profile.d/omarchy.sh, so OMARCHY_PATH is unset and every theme lookup
# resolves against an empty prefix:
#
#   omarchy-theme-set[962]: Theme 'tokyo-night' does not exist
#
# on a system where /usr/share/omarchy/themes/tokyo-night plainly exists. A
# login shell sources the profile drop-in that upstream ships for exactly this.
ExecStart=/bin/bash -lc 'omarchy-theme-set tokyo-night'
# The coding-agent tile, and the mise wrappers behind the agent names
# (docs/spec/settings.md P). Here rather than in a unit of its own because it
# wants exactly what the theme wants: once, on first login, in a login shell.
# `seed` writes eleven five-line wrappers and one .desktop and downloads
# nothing, so it costs a few milliseconds even though nobody has picked an
# agent yet.
#
# Leading `-`, so a wrapper that cannot be written does not abort the unit
# before the two lines below it run. Without it a failed seed leaves the
# first-run stamp unwritten, and every subsequent login re-applies the theme
# over whatever the user has since chosen.
ExecStart=-/bin/bash -lc 'omarchy-mobile-agent seed'
ExecStart=/usr/bin/mkdir -p %h/.local/state/omarchy/done
ExecStart=/usr/bin/touch %h/.local/state/omarchy/done/first-run
RemainAfterExit=yes

[Install]
WantedBy=default.target
EOF
ln -sf ../omarchy-mobile-first-run.service \
  /etc/skel/.config/systemd/user/default.target.wants/omarchy-mobile-first-run.service
# The user was created before this landed in skel, so copy it across too.
cp -a /etc/skel/.config/systemd "/home/$GUEST_USER/.config/" 2>/dev/null || true
chown -R "$GUEST_USER:$GUEST_USER" "/home/$GUEST_USER"

# ---------------------------------------------------------------------------
say "package repository"
# [moarchy] is how a built phone gets a fix without a reflash, and how the Store
# installs an app this project packaged rather than baked in: moarchy-store's
# helper execs `pacman -S` against its signed allowlist, and pacman can only
# reach a package that is in a sync database. A package built into the image is
# in no database at all -- it cannot be installed on demand, and once removed it
# cannot come back.
#
# Appended, never inserted. pacman resolves in file order, so ours sitting after
# core/extra/alarm/aur means an upstream package of the same name always wins.
# Nothing here should shadow the base system by accident.
#
# SigLevel = Required rather than Never: these install as root, and HTTPS alone
# says only that the bytes arrived from GitHub, not that they are ours.
# moarchy-keyring is in the session tier, so the key is already trusted by the
# time this repo is first consulted.
cat >>/etc/pacman.conf <<EOF

[$REPO_NAME]
SigLevel = Required
Server = $REPO_SERVER
EOF

# Prime the database, or a flashed image installs nothing from the repository it
# just configured. pacstrap caches the sync databases it used, and [$REPO_NAME]
# was not among them -- the build resolves everything from ALARM and the file://
# repo of our own builds -- so the guest starts life with the stanza and no
# database behind it. Fetching it here means the first `pacman -S` works before
# the phone has ever been online, and the Store's Install row does not open a
# terminal that prints "database not found" and waits.
#
# Warned about rather than fatal: a build machine that cannot reach the release
# URL still produces a usable image, one `pacman -Sy` away from working. moarchy
# learned this the hard way and documents it in image/configure.sh.
if pacman -Sy --noconfirm >/dev/null 2>&1; then
  say "[$REPO_NAME] primed -- installable before first boot"
else
  say "!! could not refresh [$REPO_NAME] -- run 'pacman -Sy' in the guest"
fi

# ---------------------------------------------------------------------------
say "provenance"
install -d /etc/omarchy-mobile
# The Omarchy pin as well as this project's own. About Omarchy reads it
# (omarchy-mobile-about): omarchy-version asks pacman for a package this image
# does not install, and upstream's own version file reads 4.0.0.alpha at v4.0.3.
cat >/etc/omarchy-mobile/release <<EOF
VERSION=$VERSION
COMMIT=$COMMIT
OMARCHY_VERSION=${OMARCHY_VERSION:-}
OMARCHY_REF=${OMARCHY_REF:-}
BUILT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
